apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-web
  namespace: payments
  labels:
    app: payments-web
    owner: payments-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-web
  template:
    metadata:
      labels:
        app: payments-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: web
          image: ghcr.io/bearh141/w10-api-141:0.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 8080
