apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: policy-controller
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.10.6
    helm:
      values: |
        webhookTimeoutSeconds: 30
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: policy-controller-webhook
      jsonPointers:
        - /spec/template/spec/containers/0/livenessProbe
        - /spec/template/spec/containers/0/readinessProbe
        - /spec/template/spec/containers/0/resources
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: policy.sigstore.dev
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: policy.sigstore.dev
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
