apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: policy-controller
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.10.6
    helm:
      parameters:
        - name: webhook.livenessProbe.timeoutSeconds
          value: "5"
        - name: webhook.readinessProbe.timeoutSeconds
          value: "5"
  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
