apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-signature-policy
spec:
  images:
    - glob: "ghcr.io/bearh141/*"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEXSynXtPCQdDgDOjO7zdxDQCgw36D
          ioHMaKQ78DBPLDVtlr7jZTiSh1gQgfv4Ye+HSwifbPRf9Kn5R5c23Hef2A==
          -----END PUBLIC KEY-----

