apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-signature-policy
spec:
  images:
    - glob: "ghcr.io/bearh141/*"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEze0UyPsxVVczrNcje2TshQSsg4Ln
          Q4BsnV6CQQ0thNgMX1ACYTHgsdUZzOHw3EIRswl9Pi9GkLOcsGKJ4zYrDQ==
          -----END PUBLIC KEY-----
